какая-то засада..
Archangel37/Lesson2_test pull request #3
Opened 2018-04-11 08:32 UTC by Archangel37

какая-то засада..

2018-04-12 07:36 UTC, ilpoli requested changes

2018-04-12 07:36 UTC, ilpoli commented on Lesson2/ParserClass.cs
> +        ///     (3) Получение сумм/вычитаний(та же сумма только число *(-1)) чисел  - Приватная, работает внутри класса
Что это за числа? (2)-(3) и т.д. ?

2018-04-13 05:26 UTC, Archangel37 commented on Lesson2/ParserClass.cs
> +        ///     (3) Получение сумм/вычитаний(та же сумма только число *(-1)) чисел  - Приватная, работает внутри класса
Для себя и для удобства порядок действий выписал, не знаю как ещё пометить приоритет - 0 - сначала получаем число double, потом вычисляем факториал (1), потом произведения используем(2), потом сумматор(3), ну а потом финально вычисляем значение выражения (4)

2018-04-15 05:32 UTC, ilpoli approved these changes

2018-04-16 06:24 UTC, merged